/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package departmentwiseemp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author hp
 */
public class DepartmentWise extends java.awt.Frame {
    Connection con = null;
    /**
     * Creates new form DepartmentWise
     */
    public DepartmentWise() {
        initComponents();
        setSize(400,300);
        con = DBConnetionUtil.connectOracle();
        if(con != null) {                        
            try {
                String sql = "select * from dept";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                while(rs.next()) {
                    choice1.add(rs.getString("dname"));
                }
            } catch (Exception e) {
                e.printStackTrace();
            }                        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        list1 = new java.awt.List();
        label2 = new java.awt.Label();
        choice1 = new java.awt.Choice();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setText("Department Wise Employees");
        add(label1);
        label1.setBounds(20, 10, 360, 20);
        add(list1);
        list1.setBounds(30, 130, 340, 150);

        label2.setText("Select Department");
        add(label2);
        label2.setBounds(70, 60, 110, 20);

        choice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice1ItemStateChanged(evt);
            }
        });
        add(choice1);
        choice1.setBounds(220, 60, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void choice1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice1ItemStateChanged
        // TODO add your handling code here:
        try {
            String s = (String)evt.getItem();
            String sql = "select empno, ename, job from emp natural join dept where dname=?";        
            PreparedStatement ps = con.prepareStatement(sql);   
            ps.setString(1, s);
            ResultSet rs = ps.executeQuery();
            list1.clear();
            while(rs.next()) {                
                String emp = rs.getString("empno")+" \t"+rs.getString("ename")+" \t"+rs.getString("job");
                list1.add(emp);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_choice1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentWise().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
