/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citysearch;

/**
 *
 * @author hp
 */
public class SearchPage extends java.awt.Frame {
    
    String cities[] = {"Mumbai", "Indore","Bhopal","Jaipur","Pune","Delhi","Banglore"};        
        
    /**
     * Creates new form SearchPage
     */
    public SearchPage() {
        initComponents();
        setSize(500,500);
        for (String city : cities) {
            list1.add(city);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        list1 = new java.awt.List();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setText("City");
        add(label1);
        label1.setBounds(30, 30, 24, 20);

        textField1.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                textField1TextValueChanged(evt);
            }
        });
        textField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField1KeyTyped(evt);
            }
        });
        add(textField1);
        textField1.setBounds(100, 30, 270, 20);
        add(list1);
        list1.setBounds(100, 80, 270, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void textField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_textField1KeyPressed

    private void textField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1KeyTyped

    private void textField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyReleased
       
    }//GEN-LAST:event_textField1KeyReleased

    private void textField1TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_textField1TextValueChanged
         String searchQuery = textField1.getText();
        setTitle(searchQuery);
        int listSize= list1.getItemCount();           
        int i=0;
        cities = list1.getItems();
        for (String city : cities) {
            list1.deselect(i);
            if(city.toLowerCase().startsWith(searchQuery.toLowerCase())) {
                list1.select(i);                                
            }
            i++;
        }
    }//GEN-LAST:event_textField1TextValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPage().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    private java.awt.List list1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
