/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package focuscolorchange;

import java.awt.Color;

/**
 *
 * @author hp
 */
public class ColorChanger extends java.awt.Frame {

    /**
     * Creates new form ColorChanger
     */
    public ColorChanger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        textField1.setText("textField1");
        textField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textField1MouseExited(evt);
            }
        });
        textField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textField1FocusLost(evt);
            }
        });
        add(textField1);
        textField1.setBounds(100, 40, 200, 30);

        textField2.setText("textField2");
        textField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textField2FocusLost(evt);
            }
        });
        add(textField2);
        textField2.setBounds(100, 110, 200, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void textField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textField1MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textField1MouseEntered

    private void textField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textField1MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textField1MouseExited

    private void textField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField1FocusGained
        // TODO add your handling code here:
        textField1.setBackground(Color.green);
    }//GEN-LAST:event_textField1FocusGained

    private void textField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField1FocusLost
        // TODO add your handling code here:
        textField1.setBackground(Color.white);
    }//GEN-LAST:event_textField1FocusLost

    private void textField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField2FocusGained
        // TODO add your handling code here:
        textField2.setBackground(Color.green);
    }//GEN-LAST:event_textField2FocusGained

    private void textField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField2FocusLost
        // TODO add your handling code here:
        textField2.setBackground(Color.white);
    }//GEN-LAST:event_textField2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorChanger().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
