/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregistration;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author hp
 */
public class Registration extends java.awt.Frame {
    
    Connection con;
    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        label6.setVisible(false);
        label6.setForeground(Color.green);
        setSize(400,300);          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label3 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        textField5 = new java.awt.TextField();
        button1 = new java.awt.Button();
        label6 = new java.awt.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setText("UserId");
        add(label1);
        label1.setBounds(28, 50, 90, 20);

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        add(textField1);
        textField1.setBounds(140, 50, 210, 20);

        label2.setText("Password");
        add(label2);
        label2.setBounds(30, 90, 110, 20);

        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        add(textField2);
        textField2.setBounds(140, 90, 210, 20);

        label3.setText("UserName");
        add(label3);
        label3.setBounds(30, 130, 80, 20);
        add(textField3);
        textField3.setBounds(140, 130, 210, 20);
        add(textField4);
        textField4.setBounds(140, 170, 210, 20);

        label4.setText("City");
        add(label4);
        label4.setBounds(30, 170, 80, 20);

        label5.setText("Email");
        add(label5);
        label5.setBounds(30, 210, 90, 20);

        textField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField5ActionPerformed(evt);
            }
        });
        add(textField5);
        textField5.setBounds(140, 210, 210, 20);

        button1.setLabel("Save");
        button1.setName(""); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(290, 260, 43, 24);

        label6.setText("label6");
        add(label6);
        label6.setBounds(40, 260, 220, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        System.out.println("some thing");
        try {
         con = DBConnectionUtil.connectOracle();   
         if(true) {
             System.out.println("Test");
            String userId = textField1.getText();
            String password = textField2.getText();
            String username = textField3.getText();
            String city = textField4.getText();
            String email =textField5.getText();
            String sql = "insert into users (user_id,pwd,uname,city,email) values (?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, userId);
            ps.setString(2, password);
            ps.setString(3, username);
            ps.setString(4, city);
            ps.setString(5, email);
            if(ps.executeUpdate()>0) {
                label6.setVisible(true);
                label6.setText("Data Inserted");
            } else {
                label6.setVisible(true);
                label6.setText("Some Error in Inserting");
                label6.setForeground(Color.red);
            }            
         } else {
             System.out.println("DBConnectionFailed");
         }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    // End of variables declaration//GEN-END:variables
}
